let
    Source = Csv.Document(File.Contents("D:\Downloads\Uncleaned_DS_jobs.csv.csv"),[Delimiter=",", Columns=15, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"index", Int64.Type}, {"Job Title", type text}, {"Salary Estimate", type text}, {"Job Description", type text}, {"Rating", type number}, {"Company Name", type text}, {"Location", type text}, {"Headquarters", type text}, {"Size", type text}, {"Founded", Int64.Type}, {"Type of ownership", type text}, {"Industry", type text}, {"Sector", type text}, {"Revenue", type text}, {"Competitors", type text}}),
    #"Extracted Text Before Delimiter" = Table.TransformColumns(#"Changed Type", {{"Salary Estimate", each Text.BeforeDelimiter(_, "("), type text}}),
    #"Inserted Literal" = Table.AddColumn(#"Extracted Text Before Delimiter", "Min Sal", each "101", type text),
    #"Reordered Columns" = Table.ReorderColumns(#"Inserted Literal",{"index", "Job Title", "Salary Estimate", "Min Sal", "Job Description", "Rating", "Company Name", "Location", "Headquarters", "Size", "Founded", "Type of ownership", "Industry", "Sector", "Revenue", "Competitors"}),
    #"Duplicated Column" = Table.AddColumn(#"Reordered Columns", "Max Sal", each [Min Sal], type text),
    #"Reordered Columns1" = Table.ReorderColumns(#"Duplicated Column",{"index", "Job Title", "Salary Estimate", "Min Sal", "Max Sal", "Job Description", "Rating", "Company Name", "Location", "Headquarters", "Size", "Founded", "Type of ownership", "Industry", "Sector", "Revenue", "Competitors"}),
    #"Added Custom" = Table.AddColumn(#"Reordered Columns1", "Role Type", each if Text.Contains([Job Title], "Data Scientist") then
"Data Scientist"
else if Text.Contains([Job Title], "Data Analyst") then
"Data Analyst"
else if Text.Contains([Job Title], "Data Engineer") then
"Data Engineer"

else if Text.Contains([Job Title], "Machine Learning") then
"Machine Learning Engineer"
else
"other"),
    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"Role Type", type text}}),
    #"Added Custom1" = Table.AddColumn(#"Changed Type1", "Location Correction", each if [Location]= "New Jersey" then ", NJ"
else if [Location] = "Remote" then ", other"
else if [Location]= "United States" then ", other"
else if [Location]= "Texas" then ", TX"
else if [Location]= "Patuxent" then ", MA"
else if [Location]= "California" then ", CA"
else if [Location]= "Utah" then ", UT"
else [Location]),
    #"Renamed Columns" = Table.RenameColumns(#"Added Custom1",{{"Location Correction", "Location Correction 1"}}),
    #"Split Column by Delimiter" = Table.SplitColumn(#"Renamed Columns", "Location Correction 1", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), {"Location Correction 1.1", "Location Correction 1.2"}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Location Correction 1.1", type text}, {"Location Correction 1.2", type text}}),
    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type2",{{"Location Correction 1.2", "Location Correction 2"}, {"Location Correction 1.1", "Location Correction 1"}}),
    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns1","Anne Rundell","MA",Replacer.ReplaceText,{"Location Correction 2"}),
    #"Renamed Columns2" = Table.RenameColumns(#"Replaced Value",{{"Location Correction 2", "State Abbreviations"}}),
    #"Duplicated Column1" = Table.DuplicateColumn(#"Renamed Columns2", "Size", "Size - Copy"),
    #"Reordered Columns2" = Table.ReorderColumns(#"Duplicated Column1",{"index", "Job Title", "Salary Estimate", "Min Sal", "Max Sal", "Job Description", "Rating", "Company Name", "Location", "Headquarters", "Size", "Size - Copy", "Founded", "Type of ownership", "Industry", "Sector", "Revenue", "Competitors", "Role Type", "Location Correction 1", "State Abbreviations"}),
    #"Renamed Columns3" = Table.RenameColumns(#"Reordered Columns2",{{"Size - Copy", "MinCompanySize"}}),
    #"Split Column by Delimiter1" = Table.SplitColumn(#"Renamed Columns3", "MinCompanySize", Splitter.SplitTextByDelimiter("to", QuoteStyle.Csv), {"MinCompanySize.1", "MinCompanySize.2"}),
    #"Changed Type3" = Table.TransformColumnTypes(#"Split Column by Delimiter1",{{"MinCompanySize.1", type text}, {"MinCompanySize.2", type text}}),
    #"Renamed Columns4" = Table.RenameColumns(#"Changed Type3",{{"MinCompanySize.1", "MinCompanySize"}, {"MinCompanySize.2", "MaxCompanySize"}}),
    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns4", each ([Competitors] <> "-1") and ([Industry] <> "-1")),
    #"Split Column by Delimiter2" = Table.SplitColumn(#"Filtered Rows", "Company Name", Splitter.SplitTextByDelimiter("#(lf)", QuoteStyle.Csv), {"Company Name.1", "Company Name.2"}),
    #"Changed Type4" = Table.TransformColumnTypes(#"Split Column by Delimiter2",{{"Company Name.1", type text}, {"Company Name.2", type number}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type4",{"Company Name.2", "Job Description"})
in
    #"Removed Columns"